### ISSUE TITLE
drawsocket.help : opening the webpage url error 

### ISSUE THREAD

**Issue by nadirB** [drawsocket/drawsocket-max#1]
Hi Rama,

Thanks for this work !

I have installed the packages and the script npm. but still have troubles to load the webpage (cf img below - chrome's developer tools' log). I tried both the latest release and the one on the repository

drawsocket: "npm drawsocket started -- please wait..."
drawsocket: "npm --scripts-prepend-node-path=true completed"
node.script: adding user html root path /Users/hecceite/Documents/Max 8/Packages/drawsocket/help/
node.script: setting node_modules path for client scripts /Users/hecceite/Documents/Max 8/Packages/drawsocket/javascript/node_modules/
node.script: [ "load webpage at", "http://localhost:3002" ]
node.script: [ "or", "http://192.168.1.56:3002" ]

![Screenshot 2022-06-29 at 18 54 11](https://user-images.githubusercontent.com/4725896/176493322-d7bffec7-d5e9-4bcc-89ca-f02cf86fe4f5.jpg)

Best

nadir B.

**Comment by ramagottfried** [comment]
hello @nadirB !  I have seen two instances recently of systems where the default npm installation folder is set by default to be global, maybe try `script npm install drawsocket --prefix ./` which will tell npm to install the dependencies in the local folder -- does that fix the issue?

**Comment by nadirB** [comment]
Yes, like a charm ! Thanks for your quick reply. (I was watching your workshop at Tenor22)

Bye

N.

**Comment by ramagottfried** [comment]
ok great! thanks for letting me know -- I should put this fix in the help patch.
